[package]
name = "huskybeammap-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
facet = "0.29.1"
facet-json = "0.29.1"
huskybeammap-types = { version = "0.1.0", path = "../huskybeammap-types" }
tungstenite = "0.28.0"
uuid = { version = "1.18.1", features = ["v4"] }
